[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"
[build.env]
PYTHON_VERSION = "3.12.5"

[deploy]
startCommand = "reflex run --env prod --port $PORT --host 0.0.0.0"